### ISSUE TITLE
Products variant sections seems funky in Mobile View

### ISSUE THREAD

**Issue by riyaz95** [ahmedkaludi/amp-woocommerce#14]
Products variant sections seems funky in Mobile Version

Ref URL: https://powermetercity.com/product/garmin-fenix-5-gps-watch/amp/
Ref: http://take.ms/KcCMz

**Comment by ahmedkaludi** [comment]
This was already fixed, we just need to check it.

**Comment by MARQAS** [comment]
Same as #2

**Comment by MohammedKaludi** [comment]
For more details about this ticket check #2
