### ISSUE TITLE
Too Many Redirects

### ISSUE THREAD

**Issue by kevin25** [ahmedkaludi/amp-woocommerce#3]
I got the Too Many Redirects issue when point to http://domain.com/shop/amp/

**Comment by ahmedkaludi** [comment]
Hey @kevin25 

I have just pushed an update, please update to 0.9.31 and it should fix the issue.

Regards,
Ahmed

**Comment by kevin25** [comment]
Thank you. I did but still the same.

**Comment by khaledMohammed000** [comment]
Hey @kevin25 please mail us your URL at team@magazine3.com, we will look into it soon 👍

**Comment by khaledMohammed000** [comment]
Hey @kevin25 can you please mail us the URL to check this issue 👍
