### ISSUE TITLE
<link rel="amphtml" of AMP WooCommerce missing after update of AMP for WP

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/amp-woocommerce#8]
https://wordpress.org/support/topic/link-relamphtml-of-amp-woocommerce-missing-after-update-of-amp-for-wp/

**Comment by khaledMohammed000** [comment]
fixed here : https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/cc12e8351551b2b41d4bb1759dc1932e3ccf639c

**Comment by MARQAS** [comment]
Working on my end

**Comment by MohammedKaludi** [comment]
Yes, tested and seems working, so closing the ticket.
